### PR TITLE
Add new  slides to Heroes page

### PR DESCRIPTION
**Pull request by khriztianmoreno**

### CODE REVIEW

**Comment by montogeek** [comment]
All those changes are trailing spaces?
Also, why the dependency update?

**Comment by khriztianmoreno** [comment]
All those changes are trailing spaces? A: Configuration editor? I do not know
Also, why the dependency update? A: The version of the current dependence does not allow me to run the task Gulp 'harp'. I use Node LTS

**Comment by khriztianmoreno** [comment]
https://github.com/shovon/grunt-harp

**Comment by montogeek** [comment]
LGTM

**Pull request merged**
